# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: 'Terraform Installer'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    displayName: 'Terraform init'
    inputs:
      command: 'init'
      allowTelemetryCollection: true

  - task: TerraformCLI@0
    displayName: 'Terraform validate'
    inputs:
      command: 'validate'
      allowTelemetryCollection: true

  - task: TerraformCLI@0
    displayName: 'Terraform plan'
    inputs:
      command: 'plan'
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'

  - task: TerraformCLI@0
    displayName: 'Terraform apply'
    inputs:
      command: 'apply'
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'
